services:
  transmission:
    image: ghcr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - USER=stream
      - PASS=123abc
    volumes:
      - transmission_data:/config:rw,async,noatime,nodiratime
      - transmission_data:/downloads:rw,async,noatime,nodiratime
      - transmission_data:/incomplete:rw,async,noatime,nodiratime
      - transmission_data:/var/log/transmission:rw,async,noatime,nodiratime
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9091 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app_network