version: '3.9'

networks:
  torrent_network:
    driver: bridge

volumes:
  logs:  # Volume para logs do Transmission
  redis_data:  # Volume para persistência de dados do Redis

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cache_middleware
      - transmission
    networks:
      - torrent_network
    restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - USER=stream
      - PASS=123abc
    volumes:
      - /home/stream/transmission/config:/config:rw,async,noatime,nodiratime
      - /home/stream/transmission/downloads:/downloads:rw,async,noatime,nodiratime
      - /home/stream/transmission/incomplete:/incomplete:rw,async,noatime,nodiratime
      - logs:/var/log/transmission
    ports:
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9091 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - torrent_network

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "always", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lfu"]
    networks:
      - torrent_network
    restart: unless-stopped

  cache_middleware:
    build:
      context: ./cache_middleware
    container_name: cache_middleware
    depends_on:
      - redis
      - transmission
    networks:
      - torrent_network
    restart: unless-stopped