apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-transmission-claim
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 900Gi
  volumeMode: Filesystem
  volumeName: media-transmission