apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-transmission
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.3.100
    path: /srv/nfs/torrent
    readOnly: false