apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-deployment
  namespace: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: linuxserver/transmission:latest
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: nfs-storage
          mountPath: /downloads
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Sao_Paulo"
      volumes:
      - name: nfs-storage
        nfs:
          server: 192.168.3.100
          path: /srv/nfs/torrent
          readOnly: false