networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24 # Define a faixa de IP da rede
    driver_opts:
      com.docker.network.host_binding_ipv4: "0.0.0.0" # Melhor desempenho na rede

x-logging:
  &default-logging
  driver: "local"
  options:
    max-size: "5m"
    max-file: "3"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.storage=/acme.json"
      - "--serverstransport.insecureskipverify=false" # Melhorar segurança
    networks:
      app_network:
        ipv4_address: 192.168.100.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/stream/traefik/acme.json:/acme.json
    logging: *default-logging
    labels:
      - "traefik.http.middlewares.compress.compress=true"
      - "traefik.http.middlewares.default-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.default-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.default-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.default-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.default-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.default-headers.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.default-headers.headers.permissionsPolicy=accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    networks:
      app_network:
        ipv4_address: 192.168.100.10
    volumes:
      - /home/stream/jellyfin/config:/config:rw # Dados de configuração persistentes
      - /opt/stream/jellyfin/cache:/cache:rw # Cache temporário usado pela aplicação
      - /home/stream/transmission/downloads/complete:/media:rw # Biblioteca de mídia
      - type: tmpfs
        target: /cache
        tmpfs:
          size: 10G
    devices:
      - /dev/dri:/dev/dri # Intel Quick Sync para transcodificação
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=https://canela-stream.com.br
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`canela-stream.com.br`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=cloudflare"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.middlewares.compress.compress=true" # Compressão HTTP
      - "traefik.http.middlewares.secure-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.secure-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.secure-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.secure-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.secure-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.secure-headers.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.secure-headers.headers.permissionsPolicy=accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"

  transmission:
        image: ghcr.io/linuxserver/transmission:latest
        container_name: transmission
        restart: unless-stopped
        networks:
          app_network:
            ipv4_address: 192.168.100.13
        ports:
          - 51413:51413/tcp    # Porta para conexões TCP do BitTorrent
          - 51413:51413/udp    # Porta para conexões UDP do BitTorrent
        volumes:
          - /home/stream/transmission/config:/config:rw
          - /home/stream/transmission/downloads:/downloads:rw
          - /home/stream/transmission/downloads/incomplete:/incomplete:rw
          - /opt/stream/transmission/logs:/var/log/transmission:rw
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
          - TRANSMISSION_RPC_ENABLED=true           # Habilita o RPC
          - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true # Requer autenticação
          - TRANSMISSION_RPC_USERNAME=admin        # Substitua 'admin' pelo usuário desejado
          - TRANSMISSION_RPC_PASSWORD=supersecure  # Substitua 'supersecure' pela senha desejada
        healthcheck:
          test: ["CMD-SHELL", "curl -sf http://localhost:9091 || exit 1"]
          interval: 30s
          timeout: 10s
          retries: 5
        logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "5"
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.transmission.rule=Host(`torrent.canela-stream.com.br`)"
          - "traefik.http.routers.transmission.entrypoints=websecure"
          - "traefik.http.routers.transmission.tls.certresolver=cloudflare"
          - "traefik.http.middlewares.compress.compress=true"    