version: '3.8'

networks:
  nextcloud_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  nextcloud:
    image: nextcloud:30.0.2
    container_name: nextcloud
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=36HBpD61l)Lj
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=128
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=10000
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    networks:
      nextcloud_network:
        ipv4_address: 192.168.100.2
    depends_on:
      - db
      - redis

  db:
    image: mariadb:latest
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=36HBpD61l)Lj
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=36HBpD61l)Lj
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      nextcloud_network:
        ipv4_address: 192.168.100.3

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    command: redis-server --requirepass senha_redis
    volumes:
      - redis:/data
    networks:
      nextcloud_network:
        ipv4_address: 192.168.100.4

  web:
    image: nginx:alpine
    container_name: nextcloud_nginx
    volumes:
      - /home/stream/nextcloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "192.168.3.202:80:80"
    depends_on:
      - nextcloud
    networks:
      nextcloud_network:
        ipv4_address: 192.168.100.5

volumes:
  mariadb:
  redis: