apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: home-media
spec:
  selector:
    app: sonarr
  ports:
    - name: http
      port: 80
      targetPort: 8989
      protocol: TCP
  type: LoadBalancer