; Aumentar limite de upload
upload_max_filesize = 16G
post_max_size = 16G

; Aumentar tempos de execução
max_execution_time = 3600
max_input_time = 3600

; Outras otimizações de PHP
memory_limit = 512M