---
- hosts: all
  gather_facts: false
  tasks:
    - name: Baixando o Script
      get_url:
        url: https://raw.githubusercontent.com/aXR6/Configurando_Rancher_Agentes/utilitarios/Subir_Confs/agentes.sh
        dest: /home/notroot/agentes.sh
        mode: 0777
    
    - name: Rodando o Script
      shell: /home/notroot/agentes.sh