---
- hosts: all
  become: yes
  tasks:

     - name: Atualizar e atualizar pacotes apt
       become: yes
       ignore_errors: yes
       failed_when: "'FAILED' in command_result.stderr"
       apt:
         upgrade: yes
         update_cache: yes
         cache_valid_time: 86400 #One day

     - name: Certifique-se de que temos um grupo 'wheel'
       group:
         name: wheel
         state: present

     - name: Permitir que o grupo 'roda' tenha sudo sem senha
       lineinfile:
         dest: /etc/sudoers
         state: present
         regexp: '^%wheel'
         line: '%wheel ALL=(ALL) NOPASSWD: ALL'
         validate: 'visudo -cf %s'

     - name: Adicionar usuários sudoers ao grupo wheel
       user:
         name: notroot
         groups: wheel
         append: yes
         state: present
         createhome: yes
         shell: /bin/bash

     - name: Crie as pastas necessárias
       file: 
         path: "{{ item }}"
         recurse: yes
         state: directory
       with_items:
         - /home/notroot/.ssh/

     - name: Copiar configuração SSHD segura
       copy: src=sshd_config_secured dest=/etc/ssh/sshd_config owner=root group=root mode=0644
       #sudo: yes

     - name: Desabilitar IPv6
       sysctl: 
         name: "{{ item }}" 
         value: '1'
         sysctl_set: yes 
         state: present
       with_items:
         - net.ipv6.conf.all.disable_ipv6
         - net.ipv6.conf.default.disable_ipv6
         - net.ipv6.conf.lo.disable_ipv6

     - name: SSHD Restart
       service: name=sshd state=restarted enabled=yes
         #sudo: yes

     - name: Copiar chaves e perfis
       copy:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         owner: notroot
         group: notroot
         mode: 0400
       with_items:
         - { src: 'authorized_keys', dest: '/home/notroot/.ssh/authorized_keys' }