apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 120Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.2.203
    path: /home/torrent
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pv-claim
  namespace: home-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
  volumeMode: Filesystem
  storageClassName: longhorn
  volumeName: media-pv