worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream transmission_backend {
        server localhost:9091;
    }

    upstream cache_middleware_backend {
        server cache_middleware:5000;
    }

    server {
        listen 80;

        location /transmission/ {
            proxy_pass http://transmission_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /cache/ {
            proxy_pass http://cache_middleware_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}