server {
    listen 80;
    server_name _;

    # Cache settings
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=jellyfin_cache:10g max_size=10g inactive=60m use_temp_path=off;

    location / {
        proxy_pass http://jellyfin:8096;  # Encaminha o tráfego para o Jellyfin
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Cache configuration
        proxy_cache jellyfin_cache;
        proxy_cache_valid 200 302 60m;   # Respostas válidas por 60 minutos
        proxy_cache_valid 404 1m;        # Respostas 404 válidas por 1 minuto
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;

        # Optimizations
        proxy_buffering on;
        proxy_buffers 32 4k;
        proxy_busy_buffers_size 8k;
        proxy_max_temp_file_size 1024m;
    }

    # Optional: Serve static files for Jellyfin directly (improves performance)
    location /static/ {
        root /media;
        autoindex on;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}