server {
    listen 80;
    server_name localhost;

    # Local de cache Redis
    location / {
        set $redis_key $uri;
        redis_pass redis_cache:6379;
        default_type text/html;

        # Configuração de fallback
        error_page 404 = @fallback;
    }

    # Rota fallback para o Jellyfin
    location @fallback {
        proxy_pass http://jellyfin:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}