version: "3.9"

networks:
  app_network:
    driver: bridge

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - app_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=http://192.168.3.202:8096
    volumes:
      - /home/stream/jellyfin/config:/config
      - /home/stream/jellyfin/cache:/cache
      - /home/stream/transmission/downloads/complete:/media
    devices:
      - /dev/dri:/dev/dri
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/stream/nginx/conf.d:/etc/nginx/conf.d
      - /home/stream/nginx/certs:/etc/nginx/certs
      - /home/stream/nginx/logs:/var/log/nginx
    depends_on:
      - memcached
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  memcached:
    image: memcached:latest
    container_name: memcached_cache
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "11211:11211"
    command: ["memcached", "-m", "256", "-c", "1024", "-v"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"