server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://jellyfin:8096; # Use o nome do serviço Docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Cache de 10GB
        proxy_cache_path /var/cache/nginx/jellyfin_cache levels=1:2 keys_zone=jellyfin_cache:10m max_size=10g inactive=60m use_temp_path=off;
        proxy_cache jellyfin_cache;
        proxy_cache_valid 200 301 302 10m;

        # Cabeçalhos para otimização
        add_header Cache-Control "public, max-age=3600";
        add_header X-Cache-Status $upstream_cache_status;

        # Compressão gzip
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        gzip_proxied any;
        gzip_min_length 1000;
    }
}