# Configuração para Jellyfin
server {
    listen 443 ssl http2;
    server_name canela-stream.com.br www.canela-stream.com.br;

    ssl_certificate /etc/nginx/certs/cloudflare.pem;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;

    location / {
        proxy_pass http://192.168.100.10:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache jellyfin_cache;
        proxy_cache_background_update on;
        proxy_cache_valid 200 302 20m;
        proxy_cache_valid 404 1m;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
    }

    location ~* \.(mp4|mkv|webm|jpg|jpeg|png|gif)$ {
        proxy_pass http://192.168.100.10:8096;
        proxy_no_cache $http_range;
        proxy_cache_bypass $http_range;
        add_header X-Cache-Status $upstream_cache_status;
        limit_rate_after 10m;
    }
}

# Configuração para Transmission
server {
    listen 443 ssl http2;
    server_name torrent.canela-stream.com.br;

    ssl_certificate /etc/nginx/certs/cloudflare.pem;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    location / {
        proxy_pass http://192.168.100.13:9091;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        limit_conn conn_limit 10;
        limit_req zone=req_limit burst=20 nodelay;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}