server {
    listen 443 ssl http2;
    server_name canela-stream.com.br;

    ssl_certificate /etc/nginx/certs/cloudflare.pem;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    # Primeira tentativa no Redis
    location / {
        set $redis_key $uri;
        redis_pass 192.168.100.12:6379;
        default_type application/json;
        error_page 404 = @fallback;

        add_header X-Redis-Cache $upstream_cache_status;
    }

    # Fallback para backend original
    location @fallback {
        proxy_pass http://192.168.100.10:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_cache jellyfin_cache;
        proxy_cache_valid 200 10m;
        add_header X-Cache-Status $upstream_cache_status;
    }

    # Streaming de mídia com cache
    location ~* \.(mp4|mkv|webm|jpg|jpeg|png|gif)$ {
        proxy_pass http://192.168.100.10:8096;
        proxy_cache jellyfin_cache;
        proxy_cache_valid 200 1h;
        limit_rate 500k;
        add_header X-Cache-Status $upstream_cache_status;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name torrent.canela-stream.com.br;

    ssl_certificate /etc/nginx/certs/cloudflare.pem;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    location / {
        set $redis_key $uri;
        redis_pass redis_backend;
        error_page 404 = @fallback;

        add_header X-Redis-Cache $upstream_cache_status;
    }

    location @fallback {
        proxy_pass http://192.168.100.13:9091;
        proxy_cache transmission_cache;
        proxy_cache_valid 200 10m;
        limit_conn conn_limit 10;
        limit_req zone=req_limit burst=20 nodelay;
    }
}