
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    # Ocultar versão do NGINX
    server_tokens off;

    # Compressão
    gzip on;
    gzip_static on;
    gzip_types text/plain text/css application/json application/javascript application/xml+rss image/svg+xml font/woff font/woff2 video/mp4 video/webm;
    gzip_min_length 1024;
    gzip_vary on;

    # Cache de proxy
    proxy_cache_path /var/cache/nginx/jellyfin levels=1:2 keys_zone=jellyfin_cache:512m max_size=40g inactive=30m use_temp_path=off;
    proxy_cache_path /var/cache/nginx/transmission levels=1:2 keys_zone=transmission_cache:256m max_size=8g inactive=15m use_temp_path=off;


    proxy_cache_lock on;
    proxy_cache_use_stale updating error timeout http_500 http_502 http_503 http_504;

    proxy_cache_key "$scheme$request_method$host$request_uri";

    proxy_buffer_size 16k;
    proxy_buffers 8 16k;
    proxy_busy_buffers_size 32k;

    # Zona de limite de requisições
    limit_req_zone $binary_remote_addr zone=req_limit:20m rate=10r/s;

    include /etc/nginx/conf.d/*.conf;
}