user  nginx;
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Configura o cache de buffer
    client_body_buffer_size 512k;
    client_max_body_size 1024M;

    upstream nextcloud {
        server nextcloud:80;
    }

    server {
        listen 80;
        server_name seu_dominio.com;

        # Redireciona para HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl http2;
        server_name seu_dominio.com;

        # Caminho para os certificados SSL (substitua pelos seus arquivos de certificado)
        ssl_certificate /etc/ssl/certs/nextcloud_cert.pem;
        ssl_certificate_key /etc/ssl/private/nextcloud_key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        # Configurações de segurança adicionais
        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;" always;
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Robots-Tag none;
        add_header X-Download-Options noopen;
        add_header X-Permitted-Cross-Domain-Policies none;

        # Configuração do cache
        fastcgi_buffers 64 4K;

        # Localização para o Nextcloud
        location / {
            proxy_pass http://nextcloud;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Ssl on;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_redirect off