apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: home-media
spec:
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: radarr-port
              containerPort: 7878
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          volumeMounts:
            - name: "media-pv"
              mountPath: /config
              subPath: configs/radarr
            - name: "media-pv"
              mountPath: /downloads/transmission
              subPath: downloads/transmission
            - name: "media-pv"
              mountPath: /downloads/complete
              subPath: downloads/complete
            - name: "media-pv"
              mountPath: /movies
              subPath: library/movies
            - name: "mounted-network-share"
              mountPath: /home/torrent/pandoraserver/video
          livenessProbe:
            httpGet:
              path: /
              port: radarr-port
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: radarr-port
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: "media-pv"
          persistentVolumeClaim:
            claimName: media-pv-claim
        - name: "mounted-network-share"
          hostPath:
            path: /home/torrent/pandoraserver/video