apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: home-media
spec:
  selector:
    app: radarr
  ports:
    - name: http
      port: 80
      targetPort: 7878
      protocol: TCP
  type: LoadBalancer