version: '3.8'

networks:
  torrent_network:
    driver: bridge
  nextcloud_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  mariadb:
  redis:

services:
  transmission:
    image: ghcr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - USER=stream
      - PASS=123abc
    volumes:
      - /home/stream/transmission/config:/config
      - /home/stream/transmission/downloads:/downloads:rw,async,noatime,nodiratime
      - /home/stream/transmission/incomplete:/incomplete:rw,async,noatime,nodiratime
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped
    #deploy:
      #resources:
        #limits:
          #cpus: "2.0"
          #memory: 512M
        #reservations:
          #cpus: "1.0"
          #memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9091 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    networks:
      - torrent_network

  nextcloud:
    image: nextcloud:30.0.2
    container_name: nextcloud
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=36HBpD61l)Lj
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=128
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=10000
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    volumes:
      - /home/stream/nextcloud/data:/var/www/html
      - /home/stream/nextcloud/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      nextcloud_network:
        ipv4_address: 192.168.100.2
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: mariadb:11.4
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=36HBpD61l)Lj
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=36HBpD61l)Lj
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      nextcloud_network:
        ipv4_address: 192.168.100.3
    restart: always

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    command: redis-server --requirepass 36HBpD
    volumes:
      - redis:/data
    networks:
      nextcloud_network:
        ipv4_address: 192.168.100.4
    restart: always

  web:
    image: nginx:alpine
    container_name: nextcloud_nginx
    volumes:
      - /home/stream/nextcloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "192.168.3.202:80:80"
    networks:
      nextcloud_network:
        ipv4_address: 192.168.100.5
    restart: always