---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: nextcloud
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "3000m"
        memory: "2Gi"
      min:
        cpu: "1000m"
        memory: "1Gi"

    - type: "Container"
      max:
        cpu: "1000m"
        memory: "2Gi"
      min:
        cpu: "500m"
        memory: "1Gi"

      default:
        cpu: "1000m"
        memory: "2Gi"
      defaultRequest:
        cpu: "500m"
        memory: "1Gi"
