apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-empty-dir-cleanup
  namespace: kube-system
spec:
  schedule: "*/1 * * * *"
  # schedule: "0 2 * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: etcd-empty-dir-cleanup
        spec:
          restartPolicy: OnFailure
          containers:
            - name: k8s-cleanup
              image: jonathanbaraldi/k8s-cleanup
              command:
                - "/bin/bash"
                - "/bin/etcd-empty-dir-cleanup.sh"
              resources:
                requests:
                  cpu: "100m"
                  memory: "50Mi"
          #nodeSelector:
          #role: master