locals {
  machine_map = {
    machines = {
      m1 = {
        name                = "ks8-vm1"
        target_node         = "dell5437"                # Nome do Servidor Proxmox
        qemu_os             = "Linux"                   # Tipo de sistema operacional
        os_type             = "cloud-init"              # Defina como cloud-init para utilizar modelos
        agent               = 1                         # Defina como 1 para habilitar o QEMU Guest Agent. Observe que você deve executar o daemon qemu-guest-agent no convidado para que isso tenha algum efeito.
        full_clone          = true                      # Defina como true para criar um clone completo ou false para criar um clone vinculado. Veja os documentos sobre clonagem para mais informações. Só se aplica quando o clone está definido.
        template            = "Debian11CloudInitAgente" # Nome do modelo usado para clonar
        vmid                = 101
        vcpus               = 2
        cores               = 2
        socket              = 1
        memory              = 3072
        balloon             = 3072                      # Memória mínima
        storage             = "35G"                     # Tamanho do disco rígido secundário atribuído como inicializável
        cpu                 = "kvm64"
        numa                = true                      # acesso não uniforme à memória (NUMA) e a fixação da CPU (afinidade do processador)
        ip_address          = "192.168.2.11"
        gateway             = "192.168.2.254"
        description         = "Máquina virtual - ks8-vm1 - para Rancher."
        ssh_user            = "notroot"
        mac_address         = "22:E2:A0:2F:92:53"
        disk_type           = "scsi"
        storage_dev         = "local-zfs"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "ks8vm1"
        hotplug             = "network,disk,cpu,memory"
        automatic_reboot    = true
        network_firewall    = false                      # o padrão é falso
        searchdomain        = "pve.datacenter.tsc"
        nameserver          = "192.168.2.200 192.168.2.201 8.8.8.8"
      }

      m2 = {
        name                = "ks8-vm2"
        target_node         = "dell5437"                 # Nome do Servidor Proxmox
        qemu_os             = "Linux"                    # Tipo de sistema operacional
        os_type             = "cloud-init"               # Defina como cloud-init para utilizar modelos
        agent               = 1                          # Defina como 1 para habilitar o QEMU Guest Agent. Observe que você deve executar o daemon qemu-guest-agent no convidado para que isso tenha algum efeito.
        full_clone          = true                       # Defina como true para criar um clone completo ou false para criar um clone vinculado. Veja os documentos sobre clonagem para mais informações. Só se aplica quando o clone está definido.
        template            = "Debian11CloudInitAgente"  # Nome do modelo usado para clonar
        vmid                = 102
        vcpus               = 2
        cores               = 2
        socket              = 1
        memory              = 3072
        balloon             = 3072                       # Memória mínima
        storage             = "35G"                      # Tamanho do disco rígido secundário atribuído como inicializável
        cpu                 = "kvm64"
        numa                = true                       # acesso não uniforme à memória (NUMA) e a fixação da CPU (afinidade do processador)
        ip_address          = "192.168.2.12"
        gateway             = "192.168.2.254"
        description         = "Máquina virtual - ks8-vm2 - para Rancher."
        ssh_user            = "notroot"
        mac_address         = "82:57:68:61:12:DD"
        disk_type           = "scsi"
        storage_dev         = "local-zfs"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "ks8vm2"
        hotplug             = "network,disk,cpu,memory"
        automatic_reboot    = true
        network_firewall    = false                      # o padrão é falso
        searchdomain        = "pve.datacenter.tsc"
        nameserver          = "192.168.2.200 192.168.2.201 8.8.8.8"
      }

      m3 = {
        name                = "ks8-vm3"
        target_node         = "dell5437"                 # Nome do Servidor Proxmox
        qemu_os             = "Linux"                    # Tipo de sistema operacional
        os_type             = "cloud-init"               # Defina como cloud-init para utilizar modelos
        agent               = 1                          # Defina como 1 para habilitar o QEMU Guest Agent. Observe que você deve executar o daemon qemu-guest-agent no convidado para que isso tenha algum efeito.
        full_clone          = true                       # Defina como true para criar um clone completo ou false para criar um clone vinculado. Veja os documentos sobre clonagem para mais informações. Só se aplica quando o clone está definido.
        template            = "Debian11CloudInitAgente"  # Nome do modelo usado para clonar
        vmid                = 103
        vcpus               = 2
        cores               = 2
        socket              = 1
        memory              = 3072
        balloon             = 3072                       # Memória mínima
        storage             = "35G"                      # Tamanho do disco rígido secundário atribuído como inicializável
        cpu                 = "kvm64"
        numa                = true                       # acesso não uniforme à memória (NUMA) e a fixação da CPU (afinidade do processador)
        ip_address          = "192.168.2.13"
        gateway             = "192.168.2.254"
        description         = "Máquina virtual - ks8-vm3 - para Rancher."
        ssh_user            = "notroot"
        mac_address         = "4E:C0:9E:89:A1:DD"
        disk_type           = "scsi"
        storage_dev         = "local-zfs"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "ks8vm3"
        hotplug             = "network,disk,cpu,memory"
        automatic_reboot    = true
        network_firewall    = false                      # o padrão é falso
        searchdomain        = "pve.datacenter.tsc"
        nameserver          = "192.168.2.200 192.168.2.201 8.8.8.8"
      }

      m4 = {
        name                = "ks8-rancher"
        target_node         = "dell5437"                 # Nome do Servidor Proxmox
        qemu_os             = "Linux"                    # Tipo de sistema operacional
        os_type             = "cloud-init"               # Defina como cloud-init para utilizar modelos
        agent               = 1                          # Defina como 1 para habilitar o QEMU Guest Agent. Observe que você deve executar o daemon qemu-guest-agent no convidado para que isso tenha algum efeito.
        full_clone          = true                       # Defina como true para criar um clone completo ou false para criar um clone vinculado. Veja os documentos sobre clonagem para mais informações. Só se aplica quando o clone está definido.
        template            = "Debian11CloudInitRancher" # Nome do modelo usado para clonar
        vmid                = 100
        vcpus               = 4
        cores               = 2
        socket              = 2
        memory              = 4096
        balloon             = 4096                       # Memória mínima
        storage             = "35G"                      # Tamanho do disco rígido secundário atribuído como inicializável
        cpu                 = "kvm64"
        numa                = true                       # acesso não uniforme à memória (NUMA) e a fixação da CPU (afinidade do processador)
        ip_address          = "192.168.2.10"
        gateway             = "192.168.2.254"
        description         = "Máquina virtual - ks8-rancher."
        ssh_user            = "notroot"
        mac_address         = "FA:58:B8:CE:04:B8"
        disk_type           = "scsi"
        storage_dev         = "local-zfs"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "ks8rancher"
        hotplug             = "network,disk,cpu,memory"
        automatic_reboot    = true
        network_firewall    = false                      # o padrão é falso
        searchdomain        = "pve.datacenter.tsc"
        nameserver          = "192.168.2.200 192.168.2.201 8.8.8.8"
      }

      m5 = {
        name                = "ns1"
        target_node         = "dellt110"                 # Nome do Servidor Proxmox
        qemu_os             = "Linux"                    # Tipo de sistema operacional
        os_type             = "cloud-init"               # Defina como cloud-init para utilizar modelos
        agent               = 1                          # Defina como 1 para habilitar o QEMU Guest Agent. Observe que você deve executar o daemon qemu-guest-agent no convidado para que isso tenha algum efeito.
        full_clone          = true                       # Defina como true para criar um clone completo ou false para criar um clone vinculado. Veja os documentos sobre clonagem para mais informações. Só se aplica quando o clone está definido.
        template            = "Debian11CloudInitComum"   # Nome do modelo usado para clonar
        vmid                = 201
        vcpus               = 1
        cores               = 1
        socket              = 1
        memory              = 1024
        balloon             = 512                        # Memória mínima
        storage             = "10G"                      # Tamanho do disco rígido secundário atribuído como inicializável
        cpu                 = "kvm64"
        numa                = true                       # acesso não uniforme à memória (NUMA) e a fixação da CPU (afinidade do processador)
        ip_address          = "192.168.2.200"
        gateway             = "192.168.2.254"
        description         = "Máquina virtual - DNS Master."
        ssh_user            = "notroot"
        mac_address         = "6E:60:3D:9C:6E:60"
        disk_type           = "scsi"
        storage_dev         = "dados"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "dnsmaster"
        hotplug             = "network,disk,cpu,memory"
        automatic_reboot    = true
        network_firewall    = false                     # o padrão é falso
        searchdomain        = "pve.datacenter.tsc"
        nameserver          = "192.168.2.200 192.168.2.201 8.8.8.8"
      }

      m6 = {
        name                = "ns2"
        target_node         = "dellt110"                # Nome do Servidor Proxmox
        qemu_os             = "Linux"                   # Tipo de sistema operacional
        os_type             = "cloud-init"              # Defina como cloud-init para utilizar modelos
        agent               = 1                         # Defina como 1 para habilitar o QEMU Guest Agent. Observe que você deve executar o daemon qemu-guest-agent no convidado para que isso tenha algum efeito.
        full_clone          = true                      # Defina como true para criar um clone completo ou false para criar um clone vinculado. Veja os documentos sobre clonagem para mais informações. Só se aplica quando o clone está definido.
        template            = "Debian11CloudInitComum"  # Nome do modelo usado para clonar
        vmid                = 202
        vcpus               = 1
        cores               = 1
        socket              = 1
        memory              = 1024
        balloon             = 512                       # Memória mínima
        storage             = "10G"                     # Tamanho do disco rígido secundário atribuído como inicializável
        cpu                 = "kvm64"
        numa                = true                      # acesso não uniforme à memória (NUMA) e a fixação da CPU (afinidade do processador)
        ip_address          = "192.168.2.201"
        gateway             = "192.168.2.254"
        description         = "Máquina virtual - DNS Slave."
        ssh_user            = "notroot"
        mac_address         = "02:C0:10:09:A7:D0"
        disk_type           = "scsi"
        storage_dev         = "dados"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "dnsslave"
        hotplug             = "network,disk,cpu,memory"
        automatic_reboot    = true
        network_firewall    = false                     # o padrão é falso
        searchdomain        = "pve.datacenter.tsc"
        nameserver          = "192.168.2.200 192.168.2.201 8.8.8.8"
      }

      m7 = {
        name                = "nfstorrent"
        target_node         = "dellt110"                # Nome do Servidor Proxmox
        qemu_os             = "Linux"                   # Tipo de sistema operacional
        os_type             = "cloud-init"              # Defina como cloud-init para utilizar modelos
        agent               = 1                         # Defina como 1 para habilitar o QEMU Guest Agent. Observe que você deve executar o daemon qemu-guest-agent no convidado para que isso tenha algum efeito.
        full_clone          = true                      # Defina como true para criar um clone completo ou false para criar um clone vinculado. Veja os documentos sobre clonagem para mais informações. Só se aplica quando o clone está definido.
        template            = "Debian11CloudInitComum"  # Nome do modelo usado para clonar
        vmid                = 200
        vcpus               = 1
        cores               = 1
        socket              = 2
        memory              = 1024
        balloon             = 512                       # Memória mínima
        storage             = "120G"                    # Tamanho do disco rígido secundário atribuído como inicializável
        cpu                 = "kvm64"
        numa                = true                      # acesso não uniforme à memória (NUMA) e a fixação da CPU (afinidade do processador)
        ip_address          = "192.168.2.203"
        gateway             = "192.168.2.254"
        description         = "Máquina virtual - NFS TORRENT."
        ssh_user            = "notroot"
        mac_address         = "1E:45:79:99:5C:7B"
        disk_type           = "scsi"
        storage_dev         = "dados"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "nfstorrent"
        hotplug             = "network,disk,cpu,memory"
        automatic_reboot    = true
        network_firewall    = false                     # o padrão é falso
        searchdomain        = "pve.datacenter.tsc"
        nameserver          = "192.168.2.200 192.168.2.201 8.8.8.8"
      }
    }
  }

  machines = lookup(local.machine_map, "machines", {})
}